# Implementing Competitive Learning from scratch using NumPy

## Importing the libraries

In [115]:
import numpy as np

## Creating the class to represent the algorithm

In [116]:
class CompetitiveLearningNN:
    def __init__(self, input_size, num_neurons, learning_rate=0.1, epochs=100):
        self.input_size = input_size
        self.num_neurons = num_neurons
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = np.random.rand(num_neurons, input_size)

    def normalize(self, data):
        return data / np.linalg.norm(data)

    def find_winner(self, data):
        normalized_data = self.normalize(data)
        activations = np.dot(self.weights, normalized_data)
        return np.argmax(activations)

    def update_weights(self, data, winner):
        normalized_data = self.normalize(data)
        self.weights[winner] += self.learning_rate * (normalized_data - self.weights[winner])

    def train(self, data):
        for epoch in range(self.epochs):
            for sample in data:
                winner = self.find_winner(sample)
                self.update_weights(sample, winner)

    def predict(self, data):
        predictions = []
        for sample in data:
            winner = self.find_winner(sample)
            predictions.append(winner)
        return predictions


## Running the algorithm and finding result for new random data

In [117]:
# Generate some random data
input_size = 5
num_neurons = 4
data = np.random.rand(10, input_size)
print("The input is : ")
print(data)

# Creating and training the competitive learning neural network
clf = CompetitiveLearningNN(input_size, num_neurons)
clf.train(data)

# Testing the predictions
test_data = np.random.rand(10, input_size)
predictions = clf.predict(test_data)

print("\n\nThe final weights after 100 epochs :")
print(clf.weights)

print("\n\nFinal predictions : ", predictions)

The input is : 
[[0.52518038 0.72643172 0.11870296 0.90016439 0.31805929]
 [0.88182966 0.53775459 0.5050117  0.62388265 0.08284808]
 [0.97008183 0.74539565 0.68555982 0.21509314 0.11414272]
 [0.73079702 0.34806613 0.03486148 0.51594802 0.18520623]
 [0.28528878 0.47831863 0.44180656 0.67924739 0.25577251]
 [0.02353798 0.85243647 0.87223069 0.84395261 0.08860424]
 [0.1297141  0.03378246 0.18805933 0.16867358 0.8309574 ]
 [0.86081531 0.27486194 0.37546666 0.12529864 0.7805619 ]
 [0.09448605 0.85247656 0.27509373 0.53246201 0.43622349]
 [0.56151355 0.03261729 0.07689887 0.22204031 0.74462664]]


The final weights after 100 epochs :
[[0.70310387 0.42784409 0.28827055 0.38708064 0.11538759]
 [0.63124296 0.12133711 0.18343812 0.16862062 0.70117365]
 [0.17918511 0.59679065 0.34573936 0.58780083 0.23806884]
 [0.14760391 0.03845378 0.21399819 0.19194575 0.94555292]]


Final predictions :  [0, 2, 2, 1, 1, 2, 2, 0, 0, 2]
